name: Test Workflow

on: push

jobs:
  build_and_test_with_memory_leak_check:
    runs-on: ubuntu-latest
    container: karcagtamas/mosze:latest
    steps:
      - uses: actions/checkout@v2
      - name: Build project
        run: make build
      - name: Memory leak check
        run: make memory_leak_check
      - name: Run I/O tests
        run: make test

  code_analysis:
    runs-on: ubuntu-latest
    container: karcagtamas/mosze:latest
    steps:
      - uses: actions/checkout@v2
      - name: Run static code analysis
        run: make static_code_analysis
      - uses: actions/upload-artifact@v2
        with:
          name: Artifact_of_secondary_code_analysis
          path: ./code_analysis_secondary.txt
