name: Test Workflow

on: push

jobs:
  build_and_test_with_memory_leak_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: g++ -std=c++17 *.cpp
      - name: Test
        run: ./run_all.sh
      - name: Install Valgrind
        run: sudo apt-get install valgrind
      - name: Memory leak check
        run: ./run_memory_leak_check.sh
      - uses: actions/upload-artifact@v2
        with:
          name: Artifact_of_memory_leak_check
          path: ./memory_leak_check.txt

  code_analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Install cppcheck
        run: sudo apt-get install cppcheck
      - uses: actions/checkout@v2
      - name: Code analysis primary (error, warning)
        run: ./run_code_analysis_primary.sh
      - name: Code analysis secondary (performance, style)
        run: ./run_code_analysis_secondary.sh
      - uses: actions/upload-artifact@v2
        with:
          name: Artifact_of_secondary_code_analysis
          path: ./code_analysis_secondary.txt
