name: Unit Tests

on: push

jobs:
  unit_testing:
    runs-on: ubuntu-latest
    container: karcagtamas/mosze:latest
    steps:
      - uses: actions/checkout@v2
      - name: Run unit tests
        run: make unittest
